In [1]:
import numpy as np

In [2]:
#!pip install numpy

In [3]:
# https://jalammar.github.io/visual-numpy/

In [4]:
my_list = [10,20,30,40]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([10, 20, 30, 40])

In [14]:
my_numpy_array= np.array(my_list)

In [15]:
type(my_numpy_array)

numpy.ndarray

In [16]:
my_numpy_array.max()

np.int64(40)

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.random.random(5)

array([0.40953653, 0.59798813, 0.41241629, 0.3250954 , 0.20943573])

In [20]:
# array arithmetic

In [21]:
my_list1 = [1,2]

In [22]:
my_list2 = [2,3]

In [23]:
my_list1 + my_list2

[1, 2, 2, 3]

In [24]:
my_numpy_array1 = np.array(my_list1)

In [25]:
my_numpy_array2 = np.array(my_list2)

In [26]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [27]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [28]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [29]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [30]:
my_numpy_array1 * 5

array([ 5, 10])

In [32]:
my_list1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [33]:
other_array = np.array([10,20,30,40,50])

In [34]:
other_array.min()

np.int64(10)

In [35]:
other_array.sum()

np.int64(150)

In [36]:
my_numpy_array1

array([1, 2])

In [44]:
#my_numpy_array1 + other_array

In [45]:
# arange & indexing

In [46]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [49]:
np_array = np.arange(0,10)

In [50]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np_array[0]

np.int64(0)

In [53]:
np_array[-1]

np.int64(9)

In [54]:
np_array[1:4:]

array([1, 2, 3])

In [55]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [56]:
np_array[2:6:2]

array([2, 4])

In [57]:
# random

In [58]:
np.random.randn(4)

array([ 0.71500708, -1.54526375, -0.82739707,  1.42115827])

In [59]:
np.random.randn(4,4)

array([[ 0.98710331, -1.06967558, -0.94832698, -0.91737869],
       [ 0.50743298,  0.09517903,  0.42013846,  0.19129773],
       [ 1.02044379,  1.77851162,  1.81347997,  2.20892892],
       [-0.47617839, -0.12152162,  0.42665767, -1.69662975]])

In [61]:
np.random.randint(1,300,5)

array([154, 141,  34, 101, 184])