In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10],[15,20]]

In [3]:
my_matrix[0]

[5, 10]

In [4]:
my_matrix[1]

[15, 20]

In [5]:
my_matrix[0][1]

10

In [6]:
# row * column

In [8]:
numpy_matrix = np.array([[5,10],[15,20]])

In [9]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [10]:
numpy_matrix[1][0]

np.int64(15)

In [11]:
numpy_matrix.sum()

np.int64(50)

In [14]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.random.random((3,2))

array([[0.51973239, 0.64914541],
       [0.63537065, 0.42384848],
       [0.22875884, 0.84897845]])

In [20]:
# matrix arithmetic

In [21]:
first_array = np.array([[10,20],[30,40]])

In [30]:
second_array = np.array([[5,15],[25,35]])

In [31]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [32]:
first_array

array([[10, 20],
       [30, 40]])

In [33]:
second_array

array([[ 5, 15],
       [25, 35]])

In [34]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [35]:
# dot product

In [38]:
first_matrix = np.array([[10,20,30]])

In [39]:
first_matrix

array([[10, 20, 30]])

In [40]:
first_matrix.shape

(1, 3)

In [43]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [44]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [45]:
second_matrix.shape

(3, 2)

In [48]:
# first_matrix * second matrix

In [49]:
result_matrix = first_matrix.dot(second_matrix)

In [50]:
result_matrix

array([[120, 180]])

In [52]:
result_matrix.shape

(1, 2)