In [1]:
import numpy as np

In [12]:
new_array = np.random.randint(1,100,20)

In [13]:
new_array

array([57, 21, 75, 41, 61, 17, 64, 67, 56, 76, 31, 50, 10, 29, 50, 24, 79,
       50, 54, 69])

In [14]:
new_array > 25

array([ True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True])

In [15]:
new_array[new_array < 25]

array([21, 17, 10, 24])

In [16]:
new_array[new_array > 25]

array([57, 75, 41, 61, 64, 67, 56, 76, 31, 50, 29, 50, 79, 50, 54, 69])

In [17]:
# transpose & reshape

In [18]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [20]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [22]:
matrix_array.shape

(3, 2)

In [24]:
matrix_array.transpose() # sütun ve satırların yerlerini değiştirir. Örn 3,2 lik iken 2,3 lük olur.
#Satırları sütuna, sütunları satıra alır.

array([[10, 20, 30],
       [20, 30, 40]])

In [26]:
matrix_array.T # ikinci kullanımı bu şekildedir.

array([[10, 20, 30],
       [20, 30, 40]])

In [27]:
random_array = np.random.random((6,1))

In [28]:
random_array

array([[0.5615511 ],
       [0.14208095],
       [0.0999573 ],
       [0.73912813],
       [0.46364652],
       [0.4096171 ]])

In [29]:
random_array.shape

(6, 1)

In [30]:
random_array.reshape(2,3)

array([[0.5615511 , 0.14208095, 0.0999573 ],
       [0.73912813, 0.46364652, 0.4096171 ]])

In [34]:
# z-score

In [35]:
data = np.array([10,12,13,15,18,25,100,105])

In [36]:
# outlier

In [37]:
mean = np.mean(data)

In [38]:
mean

np.float64(37.25)

In [40]:
data.sum() / len(data)

np.float64(37.25)

In [41]:
std = np.std(data) # standart sapma

In [42]:
std

np.float64(37.9333296719389)

In [43]:
z_scores = (data - mean) / std

In [44]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [46]:
data[z_scores > 1]

array([100, 105])

In [47]:
# math equations

In [48]:
# 2x + 3y = 8 and 5x + 7y = 19

In [49]:
# coefficient

In [50]:
A = np.array([[2,3],[5,7]])

In [51]:
# constant

In [52]:
b = np.array([8,19])

In [53]:
solution = np.linalg.solve(A,b)

In [54]:
solution

array([1., 2.])